### ISSUE TITLE
duplicate column names found: index_name

### ISSUE THREAD

**Issue by xoco70** [timescale/outflux#81]
When I try to transfer schema, I get: 

```
outflux schema-transfer sun measures --input-server=https://influx.company.com --output-conn="dbname=sun user=julien password=sun" --schema-strategy=DropAndCreate
2020/08/12 08:42:53 Selected input database: sunchain
2020/08/12 08:42:53 Overriding PG environment variables for connection with: dbname=sun user=julien password=sun
2020/08/12 08:42:53 pipe_measures starting execution
2020/08/12 08:42:53 Discovering influx schema for measurement: measures
2020/08/12 08:42:54 could not transfer schema for measurement 'measures'
pipe_measures: could not prepare extractor
pipe_measures_ext: could not fetch data set definition for measure: measures
duplicate column names found: index_name
```
Yet, it is true, I have `index_name`, and `index_name_1` in my measurement. But as it is not possibe to drop a field in Influx, how should I deal with it ? it would be no problem to import it, and then I would be able to delete duplicated column in postgres

**Comment by invernizzie** [comment]
@xoco70 the problem is that you don't have `index_name` and `index_name_1`, but rather an `index_name` tag and an `index_name` field. A way around it is to migrate points in influxdb to the right schema first, then attempt the Outflux migration again.

For example, if you want `index_name` to be a tag you'll need to query for all points with the `index_name` field and re-insert them with the `index_name` tag (using the value from the field, of course).

After you've reinserted your data in the right format, you can delete all points where `index_name` is a field, which may be tricky depending on the data; if the reason for having a field and tag name collision is that you turned a field into a tag (or vice-versa) there should be a moment in time where you can make the time and make the delete conditional on it, e.g.

```DELETE FROM measures WHERE time < '2019-08-07T05:04:03Z';```
